### ISSUE TITLE
[FEATURE] move `kumi.hpp` to `kumi/tuple.hpp` 

### ISSUE THREAD

**Issue by ldalessa** [jfalcou/kumi#6]
**Is your feature request related to a problem? Please describe.**

I think now that Kumi is its own repository, it might make some sense to change the structure from `include/kumi.hpp` to `include/kumi/tuple.hpp`. This would allow users to `#include <kumi/tuple.hpp>` which is a lot easier to understand for new programmers that aren't familiar with what `kumi.hpp` might mean.

**Comment by jfalcou** [comment]
Good point !
